---
title: "Module 1"
author: "Econ 771: Health Economics II"
date: 'August 25 through September 15'
output: 
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    theme: darkly
    number_sections: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache.path = '_cache/')
```

# Overview 
This is the guide for **Module 1**, which covers hospital objective functions and responses to financial incentives. 


# Learning objectives
1. Synthesize the literature on hospital ownership type and its effects on healthcare outcomes
2. Recognize identification strategies in applied empirical work
3. Identify potential barriers to "selection on observables" and difference-in-differences in practice
4. Analyze real data on hospital ownership type, prices, and quality
5. Describe the Medicare prospective payment system and the idea of "upcoding" in claims data


# Econometrics issues
1. Selection on observables (not really an identification strategy...more of an assumption to facilitate causal inference with purely observational data)
2. Difference-in-differences and parallel trends
3. Event studies and time varying treatment effects


# Main datasets
1. [HCRIS](https://github.com/imccart/HCRIS)
2. [Provider of Services](https://github.com/asacarny/provider-of-services)
3. [Hospital Compare](https://github.com/asacarny/hospital-compare)
4. [Physician Fee Schedule](https://github.com/imccart/PFS_Update_2010)
5. [IPPS Final Rule Files](https://data.nber.org/data/cms-impact-file-hospital-inpatient-prospective-payment-system-ipps.html)



# Schedule and slides

Below is a preliminary schedule of classes and specific papers we'll cover. This matches the list of papers in the syllabus, just with a little more detail. Links to slides (where available) are included for each class. 


### Class 2, 8/25
**Theoretical models of not-for-profits**<br>
I'll present some details on models of the not-for-profit hospital from Dranove (1988), Newhouse (1970), and Pauly (1978). These are theoretical papers proposing different models of hospital behaviors, such as a purely utility maximizing firm or a physician's owned cooperative. We'll also discuss some institutional details of the hospital market and the prevalence of private not-for-profit hospitals.

- My [slides](slides-class2.html) on hospital objective functions and not-for-profits


### Class 3, 8/27
**Empirical evidence on ownership type**<br>
Today we'll discuss some empirical work focusing on differences in behavior between for-profit versus not-for-profit hospitals. We'll cover the following papers: Duggan (2000), Horwitz and Nichols (2009), Bayindir (2012). Note that Horwitz and Nichols (2009) and Bayindir (2012) are combined in the class presentations. Both of those papers are closely related and so it makes sense to present those papers together. The papers are also relatively short.

Presenters:

- My [slides](slides-bayindir-horwitz.html) for Bayindir (2012) and Horwitz and Nichols (2009)
- Alexandra's [slides](../student-presentations/manta-20200827.pdf) for Duggan (2000)

### Class 4, 9/1
**Response to Medicare payment changes**<br>
This class focuses on hospital responses to Medicare payment changes. We'll discuss two responses in particular: 1) hospital "upcoding", with Dafny (2005); and hospital purchases of physician practices, in Dranove and Ody (2019). The general theme in both (and many other) papers is that hospitals respond to financial incentives and do not appear to be fully altruistic firms.

Presenters:

- Xin's [slides](../student-presentations/xin-20200901.pdf) will present Dranove and Ody (2019)

### Class 5, 9/3
**Hospital cost-shifting**<br>
Today's papers are both from David Dranove (and co-authors)...Dranove (1988) and Dranove et al. (2017). They extend the idea from 8/31 in that this literature considers negotiated prices (between a commercial insurer and a hospital) as another potential outcome affected by changes in Medicare payments. 

I will briefly present the Dranove (1988) paper in the beginning of class. I'll also discuss the main source of debate in this literature. Dranove et al. (2017) is the only student-led presentation for this class.

- **Update:** Since we've already talked about cost-shifting, I'll use this class to talk about Dafny (2005). My slides are [here](slides-dafny2005.html).

### Class 6, 9/8
**Response to insurance policies**<br>
Whereas the papers on 8/31 and 9/2 deal with hospital responses to changes in Medicare payments, today's papers consider more general changes to insurance policies. The papers for today are Batty and Ippolito (2017), Eliason et al. (2018), and Geruso and Layton (2020).

Presenters:

- Alexandra's [slides](../student-presentations/manta-20200908.pdf) for Batty and Ippolito (2017)
- Drew's [slides](../student-presentations/drew-20200908.html) for Eliason et al. (2018)


### Class 7-8, 9/10 and 9/15
**Workshop days!**<br>
We'll work on the first empirical assignment in class. We'll focus on accessing the data using GitHub and AWS, cleaning the data, and implementing the relevant identification strategy. See [exercise 1](../assignments/exercise1.html) for more details on this assignment. The assignment is due by **Friday, September 18th**.

- My slides available [here](slides-exercise1.html).