---
title: "Module 3: Information Disclosure"
date: 'Fall 2022'
output: 
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    number_sections: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache.path = '_cache/')
```

# Overview 
This is the guide for **Module 3**, which covers healthcare decision-making and the role of transparency/disclosure in healthcare. Our empirical exercise considers inertia in healthcare decision-making and its potential effects on insurance prices.


# Learning objectives
1. Synthesize the literature on "consumerism" in healthcare and the effects of information disclosure
2. Describe the different initiatives for price and quality transparency healthcare
3. Employ regression discontinuity designs for causal inference
4. Analyze real data on Medicare Part D



# Causal inference topics
1. Strict and fuzzy regression discontinuity design
2. Testing regression discontinuity assumptions
3. Binning and bandwidth selection for strict RD


# Main datasets
1. [Medicare Advantage](https://github.com/imccart/Medicare-Advantage)
2. [Medicare Part D](https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/MCRAdvPartDEnrolData)
3. [Replication files for Ericson (2014)](https://www.aeaweb.org/articles?id=10.1257/pol.6.1.38)



# Schedule and slides

Below are links to specific content for each class in this module. We'll fill this in as we go through the semester.