---
title: "Module 0: Introduction"
date: 'Fall 2022'
output: 
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    number_sections: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache.path = '_cache/')
knitr::opts_chunk$set(echo = TRUE, fig.align="center")
```

# Overview 
This is the guide for **Module 0**, which is really just an introduction to the class. To that end, the first thing you should do for the class is read the [syllabus](../syllabus/syllabus-771.pdf).


# Learning objectives
1. Understand the structure of the class and assignments
2. List some key areas of the economics of healthcare
3. Explain causal inference in the context of the potential outcomes framework
4. Estimate average treatment effects with a selection on observables assumption


# Causal inference topics
1. Introduction to causal inference and potential outcomes
2. Estimators based on regression, matching, and weighting
3. Doubly-robust estimation


# Schedule and slides

Below are links to specific content for each class in this module. We'll fill this in as we go through the semester.

- **Wednesday, 8/24:** Introduction to the economics of healthcare
- **Monday, 8/29:** Introduction to causal inference