---
title: "Class Schedule"
---

```{r dates_bib, include=FALSE}
start <- as.Date("2022-08-24")
advdate <- function(adv) {
 twed <- start + 7*floor(adv/2)
 tmon <- twed-2
 tmon <- format(tmon, format="%m/%d")
 twed <- format(twed, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tday <- ifelse( (adv %% 2) == 0, tmon,twed)
 tmp <- paste("Class ",zadv,sep='',", ", tday)
 return(tmp)
}
```

Below is a preliminary course outline for this semester. For a more complete reading list each day as well as more detail on course policies, please see the full syllabus [here](syllabus/syllabus-771.pdf). I'll post links to paper presentations as they are available.


## [Module 0: Kicking things off!](modules/module0.html)

  - `r advdate(1)`: Introduction to the economics of healthcare and causal inference. 
      - [Intro to healthcare slides](slides/01-intro-health.html)
      - [Intro to causal inference slides](slides/01-intro-causal-inference.html)

## [Module 1: Hospitals](modules/module1.html)

  - `r advdate(2)`: Background and institutional details. 
      - [Background slides](slides/01-1.html)
      - [Chang and Jacobson (2010), What do nonprofit hospitals maximize?](slides/student/katie-20220829.pdf), presented by Katie      
      - [Bayindir (2012), Hospital ownership and treatment choices](slides/student/pablo-20220829.pdf), presented by Pablo
  - `r advdate(3)`: Hospitals and financial incentives, part I
      - [Dafny (2005), How do hospitals respond to price changes?](slides/student/wonjun-20220831.pdf), presented by Wonjun
      - [Eliason et al. (2018), Strategic patient discharge: The case of long-term care hospitals](slides/student/kayan-20220831.pdf), presented by Ka Yan
      - [Gupta (2021), Impacts of performance pay for hospitals: The readmissions reduction program](slides/student/rachel-20220831.pdf), presented by Rachel
  - `r advdate(4)`: Labor Day, no class
  - `r advdate(5)`: Hospitals and financial incentives, part II
      - [Batty and Ippolito (2017), Financial incentives, hospital care, and health outcomes: Evidence from fair pricing laws](slides/student/jingquan-20220907.pptx), presented by Jingquan
      - [Lee (2020), How do hospitals respond to managed care? Evidence from at-risk newborns](slides/student/amy-20220907.pdf), presented by Amy
  - `r advdate(6)` - `r advdate(8)`: Empirical application with DD
      - [Basics of Panel Data and Fixed Effects](slides/02-1.html)
      - [Difference-in-Differences the "Old" Way](slides/02-2.html)
      - [Difference-in-Differences the "New" Way(s)](slides/02-3.html)
      - [Discussion of Assignment](slides/02-4.html)

## [Module 2: Physicians](modules/module2.html)

  - `r advdate(9)`: Background and institutional details
      - [Finkelstein, Gentzkow and Williams (2016), Sources of Geographic Variation in Health Care: Evidence from Patient Migration](slides/student/pablo-20220921.pdf), presented by Pablo
      - [Molitor (2018), The Evolution of Physician Practice Styles: Evidence from Cariologist Migration](slides/student/rachel-20220921.pdf), presented by Rachel
  - `r advdate(10)`: Physician agency, financial incentives, and referrals
      - [Clemens and Gottlieb (2014), Do physicians' financial incentives affect medical treatment and patient health](slides/student/wonjun-20220926.pdf), presented by Wonjun
      - [Zeltzer (2020), Gender homophily in referral networks: Consequences for the Medicare physician earning gap](slides/student/pablo-20220926.pdf), presented by Pablo
      - [Chernew et al (2021), Physician agency, consumerism, and the consumption of lower-limb MRI scans](slides/student/martha-20220926.pptx), presented by Martha
  - `r advdate(11)`: Physician learning
      - [Crawford and Shum (2005), Uncertainty and Learning in Pharmaceutical Demand](slides/student/jungjae-20220928.pdf), presented by Jung Jae
      - [Sarsons (2018), Interpreting Signals in the Labor Market: Evidence from Medical Referrals](slides/student/paul-20220928.pdf), presented by Paul
      - [Johnson (2011), Ability, Learning, and the Career Path of Cardiac Specialists](slides/student/rachel-20220928.pdf), presented by Rachel
  - `r advdate(12)` - `r advdate(13)`: Empirical application with IV
      - [Introduction to Instrumental Variables](slides/03-1.html)
      - [Instrumental Variables Assumptions and Interpretation](slides/03-2.html)
  - `r advdate(14)`: Fall break
  - `r advdate(15)`: Empirical application with IV, cont'd
      - [Common IV Designs](slides/03-3.html)

## [Module 3: Information disclosure](modules/module3.html)

  - `r advdate(16)`: Patient decision-making
      - [Ketcham et al (2012), Sinking, Swimming, or Learning to Swim in Medicare Part D](slides/student/jingxuan-20221017.pdf), presented by Jingxuan
      - [Gaynor et al (2016), Free to Choose? Reform, Choice, and Consideration Sets in the English National Health Service](slides/student/katie-20221017.pdf), presented by Katie
  - `r advdate(17)`: Inertia in health insurance choice
      - [Handel (2013), Adverse Selection and Inertia in Health Insurance Markets](slides/student/amy-20221019.pdf), presented by Amy
      - [Ericson (2014), Consumer Inertial and Firm Pricing in the Medicare Part D Prescription Drug Insurance Exchange](slides/student/nixon-20221019.pdf), presented by Nixon
  - `r advdate(18)`: Effects of quality disclosure
  - `r advdate(19)`: Effects of price disclosure
  - `r advdate(20)` - `r advdate(21)`: Empirical application with RD

## [Module 4: Healthcare competition and industrial organization](modules/module4.html)

  - `r advdate(22)`: Competition in price and quality
  - `r advdate(23)`: Measuring hospital markets and market power
  - `r advdate(24)`: "Structure-Conduct-Performance"
  - `r advdate(25)`: Bargaining framework
  - `r advdate(26)`: No meeting today. Class rescheduled for December 2  
  - `r advdate(27)`: Effects of mergers or closures (**virtual class**)
  - `r advdate(28)`: Out-of-market mergers
  - `r advdate(29)`: Vertical integration
  - 12/02 (rescheduled from 11/21) and `r advdate(30)`: Empirical application with demand estimation
