---
title: "Module 2"
author: "Econ 771: Health Economics II"
date: 'September 17 through October 1'
output: 
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    theme: darkly
    number_sections: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache.path = '_cache/')
```

# Overview 
This is the guide for **Module 2**, which covers issues related to physician agency and treatment decisions.

# Learning objectives
1. Synthesize the literature on physician agency and differentiate between agency and "supplier-induced" demand
2. Recognize identification strategies in applied empirical work
3. Identify potential barriers to instrumental variables in practice
4. Analyze real data on physician behaviors and practice characteristics using publicly available data sources
5. Describe the physician fee schedule and how Medicare pays for Part B services


# Econometrics issues
1. Instrumental variables and required assumptions
2. Treatment effects with IV
3. Using predictions as instruments


# Main datasets
1. [Physician Compare](https://data.medicare.gov/data/physician-compare)
2. [Area Health Resources Files](https://data.hrsa.gov/topics/health-workforce/ahrf)
3. [Medicare Advantage](https://github.com/imccart/Medicare-Advantage)
4. [Provider Utilization and Payment Data](https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/Medicare-Provider-Charge-Data/Physician-and-Other-Supplier)
5. [NPPES](https://www.cms.gov/Regulations-and-Guidance/Administrative-Simplification/NationalProvIdentStand/DataDissemination)
6. [National Hospital Discharge Survey](https://www.cdc.gov/nchs/nhds/index.htm)



# Schedule

### Class 9, 9/17
**The agency problem in healthcare**<br>
We typically think of agency as a contract problem in which the goal is to devise a contract that incentivizes maximum (unobservable) effort subject to relevant constraints. In the healthcare context, however, the agency problem simply reflects the different set of incentives faced by the physician versus the patient. The physician acts as an agent on behalf of the patient, but they may not act in a way that maximizes the patient's objective function. In this class, I'll present some basic theory of the physician agency problem and the role of fee-for-service versus capitated payment models. The lecture material is based entirely on the handbook chapter from McGuire (2000).

- My intro slides for physician agency are [here](slides-agency.html)


### Class 10, 9/22
**Supply-side variation in healthcare**<br>
The literature doesn't always discuss their analysis in the context of agency problems, but in many cases, agency problems represent the underlying mechanism for overutilization of healthcare services. Today's papers -- Finkelstein, Gentzkow, and Williams (2016) and Molitor (2018) -- exploit patient or physician "movers" to examine the effects of practice styles on healthcare utilization. 

The underlying idea in both papers is that physicians have a certain way of practicing, regardless of patient preferences. So when patients go to a new area where physicians are more aggressive, those patients will receive more care, and when physicians join practices that are more agressive, they will begin practicing in a more agressive way. The notion of patient and physician "movers" has become a popular identification strategy in the literature, and we'll discuss some of the merits and drawbacks of this strategy.

- Hanna's slides for Finkelstein, Gentzkow, and Williams (2016) are [here](../student-presentations/hanna-20200922.pdf)
- Drews's slides for Molitor (2018) are [here](../student-presentations/drew-20200922.pdf)


### Class 11, 9/24
**Physician response to payment changes**<br>
The papers from 9/16 take area practice styles as given and examine how utilization or individual practice styles vary as people move in and out of different areas. For today, we'll look at practice styles within an area and see how those practice styles change with financial incentives. Gruber and Owings (1996) is an older paper but important in the literature. It envisions healthcare services as being highly maleable by physicians and tests whether physicians encourage patients to pursue certain services when the physician suffers a negative financial shock. The more recent paper, Clemens and Gottlieb (2014), considers how Medicare payments affect physician practice styles. 

- Swati's slides for Gruber and Owings (1996) are [here](../student-presentations/swati-20200924.pdf)


### Class 12, 9/29
**Physician spillovers**<br>
Today we'll look at a couple of papers that study how changes in one healthcare segement (e.g., public insurance policies) affect other segments (e.g., commercial insurance patients). Clemens and Gottlieb (2017) is about spillovers from public payment policies onto the commercial insurance market, and Baicker, Chernew, and Robbins (2013) is about spillovers from Medicare managed care (the private insurance component of Medicare) onto Medicare patients. 

Hopefully it's clear from these papers how difficult it is to study healthcare in a general equilibrium setting...Medicare policies affect commercial insurers, and changes in the commercial insurance market affect how physicians treat Medicare patients. On top of that, there are practice level changes that affect physician behaviors, which of course affects patients.

- Nada's slides for Baicker, Chernew, and Robbins (2013) [here](../student-presentations/nada-20200929.pdf)


### Class 13, 10/01
**Workshop day!**<br>
Today we'll work on the second empirical assignment in class. We'll focus on accessing the data using GitHub and AWS, cleaning the data, and implementing the relevant identification strategy. See [exercise 2](../assignments/exercise2.html) for more details on this assignment. The assignment is due by **Friday, October 9th**.

- My slides for IV and our MA data are [here](slides-exercise2.html)