---
title: "Module 4"
author: "Econ 771: Health Economics II"
date: 'October 22 through November 24'
output: 
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    theme: darkly
    number_sections: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache.path = '_cache/')
```

# Overview 
This is the guide for **Module 4**, the last module of the class. Over these last few weeks, we'll cover healthcare competition and the effects of mergers and closures. Most of this will deal with hospitals but we'll have some discussion of vertical integration between hospitals and physicians as well as some papers on concentration in the dialysis industry.


# Learning objectives
1. Synthesize the literature on hospital competition and its effects on prices and quality
2. Recognize identification strategies in applied empirical work
3. Employ modern techniques for measuring hospital markets
4. Analyze real data on hospital prices
5. Describe the negotiation process between commercial insurance firms and hospitals, and distinguish between charges, costs, and prices


# Econometrics issues
1. Demand estimation with market-level data
2. Empirical issues in measuring hospital markets


# Main datasets
1. [HCRIS](https://github.com/imccart/HCRIS)
2. [Provider of Services](https://github.com/asacarny/provider-of-services)
3. [Measuring Hospital Markets](https://github.com/graveja0/health-care-markets)
4. [Hospital Service Area Files](https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/Hospital-Service-Area-File/index)



# Schedule

### Class 19, 10/22
**Competition in price and quality**<br>
No student presentations today. Instead, I'll present some basics on the nature of competition when firms set both prices and quality. The main takeaway--theory doesn't tell us much about the effects of competition in this case. It really depends on the dimension by which customers are most responsive (price or quality).

- My slides on competition are [here](slides-competition.html)


### Class 20, 10/27
**Measuring hospital market power**<br>
Today's class is about how we measure market power. The only paper for today is Dranove (2016), which provides a nice comparison of different measures in the literature.

- My slides measuring market power are [here](slides-markets.html)

### Class 21, 10/29
**Evidence from "structure-conduct-performance" studies**<br>
Kessler and McClellan (2000) is one of the first healthcare studies in this literature. I label it as a "structure-conduct-performance" study because it takes a reduced form approach and attempts to capture the "structure" of the market with some summary statistic, assumes some conduct results from the structure, and then examins the outcome (or "performance"). This was a standard empirical approach in the early days of industrial organization. 

Cooper et al. (2019) provides an excellent set of summary statistics and regression analysis of hospital pricing and industrial organization of healthcare markets. Their analysis is not necessarily causal but is an important set of empirical facts nonetheless. 

- Hanna's slides on Cooper et al. (2019) are [here](../student-presentations/hanna-20201029.pdf)
- Swati's slides on Kessler and McClellan (2000) are [here](../student-presentations/swati-20201029.pdf)


### Class 22, 11/3
**Competition in a bargaining model**<br>
Ho and Lee (2017) is not the first paper to present a bargaining model and estimate the structure IO model with data; however, this is one of the most complete models of the insurer/hospital bargaining process and is therefore the one we'll focus on in this class.


### Class 23, 11/5
**Evidence from mergers and closures**<br>
Dafny (2009) looks specifically at the effects of a hospital merger on hospital prices. As opposed to the "structure-conduct-performance" approach, this analysis compares markets in which there was a merger to those in which there was no merger and examines the relative changes in prices. 

- Fabrice's slides for Dafny (2009) are [here](../student-presentations/fabrice-20201105.pdf)

### Class 24, 11/10
**Evidence from out-of-market mergers**<br>
Dafny, Ho, and Lee (2019) examines the effects of "cross-market" mergers (i.e., hospital A in Atlanta mergers with hospital B in Savannah). They investigate a few potential mechanisms from such mergers, ultimately settling on the "common consumer" mechanism in which insurers negotiate with both hospitals so that the merger provides the joined system with more bargaining leverage even though the hospital markets themselves (Atlanta and Savannah, in our example) are distinct. Schmitt (2018) also considers out-of-market mergers; however, he considers them in the context of changing the extent to which different hospitals compete in other markets. In other words, his analysis uses out-of-market mergers as an event that changes the "pairwise overlaps" of hospitals in an otherwise unrelated market. 

- My sldies for Dafny, Ho, and Lee (2019) are [here](slides-dafny.html)

### Class 25, 11/12
**Mergers and acquisitions in dialysis**<br>
So far, we've focused exclusively on hospital markets, but there are some very interesting studies done on other aspects of healthcare. Eliason et al. (2020) is one such study on the dialysis industry.

- Linh's slides on Eliason et al. (2020) are [here](../student-presentations/linh-20201112.pdf)

### Class 26, 11/17
**Vertical integration between hospitals and physicians**<br>
One of the biggest changes to the U.S. healthcare delivery system in the past 20 years is the relationships between physicians and hospitals. Around 2000, less than 5% of all physician practices were owned by a hospital. Today, over 1/3rd of physician practices are owned by hospital systems. Given the physician's important role as an agent to the patient, this change in the physician/hospital relationship has potentially important consequences for the amount and quality of care delivered. Also, in a bargaining context, this change in physician/hospital relationships has important consequences for prices.  Koch, Wendling, and Wilson (2017) examines the effects of physician/hospital integration on the quantity of care. Lin, McCarthy, and Richards (2020) examines the effects of physician/hospital integration on hospital prices.

- Xin's slides on Koch et al. (2017) are [here](../student-presentations/xin-20201117.pdf)

### Class 27-28, 11/19 and 11/24
**Workshop days!**<br>
We'll work on the fourth (and final) empirical assignment in class. For this assignment, instead of considering a causal inference strategy, we're going to think about how to measure hospital markets and how to estimate demand for hospital services. See [exercise 4](../assignments/exercise4.html) for more details on this assignment. The assignment is due by **Tuesday, November 24th**.






